mdnazisharman2803/leetcode-challenge

Day-24/ImplementStackusingQueues.cpp
Day-24/UglyNumber.cpp

Day 24th problems done

---

Day-25/CountNodesEqualtoAverageofSubtree.cpp
Day-25/ValidParentheses.cpp

Day-25 completed

---

Day-26/Largest3Same-DigitNumberinString.cpp
Day-26/LetterCombinationsofaPhoneNumber.cpp

Day 26 completed

---

Day-27/132Pattern.cpp
Day-27/CombinationSumIII.cpp

Day-27 done

---

Day-28/Next Permutation.cpp
Day-28/PermutationsII.cpp

Day28 completed

---

Day-29/LongestWordinDictionary.cpp
Day-29/PopulatingNextRightPointersinEachNodeII.cpp

Day-29 completed

---

Day-30/ArithmeticSubarrays.cpp
Day-30/SumofSubarrayRanges.cpp

Day-30 completed

---

Day-31/FindtheDuplicateNumber.cpp
Day-31/MaximumSumCircularSubarray.cpp

Day-31 completed

---

Day-32/ShortestPathinBinaryMatrix.cpp
Day-32/UniqueNumberofOccurrences.cpp

Day-32 completed

---

Day-33/CoinChange.cpp
Day-33/UniquePathsII.cpp

Day-33 Completed

---

Day-34/DiagonalTraverse.cpp
Day-34/Searcha2DMatrix.cpp
Day-34/SpiralMatrix.cpp
Day-34/TransposeMatrix.cpp

Day-34 completed

---

Day-35/LargestNumber.cpp
Day-35/OnesandZeroes.cpp
Day-35/SortCharactersByFrequency.cpp

Day-35 completed

---

Day-36/FindAllDuplicatesinanArray.cpp
Day-36/FindGreatestCommonDivisorofArray.cpp
Day-36/LongestValidParentheses.cpp
Day-36/Numberof1Bits.cpp

Day-36 completed

---

Day-37/LongestIncreasingSubsequence.cpp
Day-37/RussianDollEnvelopes.cpp

Day-37 completed

---

Day-39/FindNumberswithEvenNumberofDigits.cpp
Day-39/SquaresofaSortedArray.cpp

Day-39 completed

---

Day-40/CheckIfNandItsDoubleExist.cpp
Day-40/RangeSumQuery2DImmutable.cpp
Day-40/ValidMountainArray.cpp

Day-40 completed

---

Day-41/NQueens.cpp
Day-41/ReplaceElementswithGreatestElementonRightSide.cpp

Day-41 completed

---

Day-42/HeightChecker.cpp
Day-42/NQueensII.cpp

Day-42 completed

---

Day-43/IntersectionofTwoLinkedLists.cpp
Day-43/PermutationinString.cpp

Day-43 completed

---

Day-45/DesignLinkedList.cpp
Day-45/RemoveNthNodeFromEndofList.cpp
Day-45/RemovePalindromicSubsequences.cpp
Day-45/ReverseLinkedList.cpp

Day-45 completed

---

Day-47/CheckifBinaryStringHasatMostOneSegmentofOnes.cpp
Day-47/RemoveDuplicatesfromSortedListII.cpp
Day-47/ReverseLinkedListII.cpp

Day-47 completed

---

Day-48/MinimumOperationstoReduceXtoZero.cpp
Day-48/OddEvenLinkedList.cpp
Day-48/PartitionList.cpp

Day-48 completed

---

Day-49/LinkedListCycle.cpp
Day-49/LinkedListCycleII.cpp
Day-49/MaximumErasureValue.cpp
Day-49/MiddleoftheLinkedList.cpp
Day-49/ReorderList.cpp

Day-49 completed

---

Day-50/AddTwoNumbersII.cpp
Day-50/PalindromeLinkedList.cpp
Day-50/RemoveLinkedListElements.cpp
Day-50/SortList.cpp
Day-50/SwappingNodesinaLinkedList.cpp
Day-50/Triangle.cpp

Day-50 completed

---

Day-51/DeleteOperationforTwoStrings.cpp
Day-51/EvaluateReversePolishNotation.cpp
Day-51/MinStack.cpp
Day-51/ReverseWordsinaString.cpp
Day-51/ReverseWordsinaStringIII.cpp

Day-51 completed

---

Day-52/LongestStringChain.cpp
Day-52/NextGreaterElementI.cpp
Day-52/NextGreaterElementII.cpp
Day-52/OnlineStockSpan.cpp

Day-52 completed

---

Day-53/DesignCircularDeque.cpp
Day-53/DesignCircularQueue.cpp
Day-53/ImplementQueueusingStacks.cpp

Day-53 completed

---

Day-54/BinaryTreeCameras.cpp
Day-54/TrappingRainWater.cpp

Day-54 completed

---

Day-55/LargestRectangleinHistogram.cpp
PrefixandSuffixSearch.cpp

Day-55 completed

---

Day-57/BalancedBinaryTree.cpp
Day-57/DiameterofBinaryTree.cpp
Day-57/ShortEncodingofWords.cpp

Day-57 completed

---

Day-58/BinaryTreeLevelOrderTraversal.cpp
Day-58/BinaryTreeLevelOrderTraversalII.cpp
Day-58/BinaryTreePaths.cpp
Day-58/MaximumDepthofBinaryTree.cpp

Day-58 completed

---

Day-59/BinaryTreeTilt.cpp
Day-59/DeleteLeavesWithaGivenValue.cpp
Day-59/MaximumLevelSumofaBinaryTree.cpp
Day-59/MinimizeDeviationinArray.cpp

Day-59 completed

---

Day-60/BinaryTreeRightSideView.cpp
Day-60/ConstructBinaryTreefromInorderandPostorderTraversal.cpp
Day-60/ConstructBinaryTreefromPreorderandInorderTraversal.cpp
Day-60/FlattenBinaryTreetoLinkedList.cpp
Day-60/LowestCommonAncestorofaBinaryTree.cpp
Day-60/MinimumDepthofBinaryTree.cpp

Day-60 completed

---

Day-61/CourseScheduleIII.cpp
Day-61/NondecreasingArray.cpp

Day-61 completed

---

Day-62/DeleteNodeinaBST.cpp
Day-62/InsertintoaBinarySearchTree.cpp
Day-62/LowestCommonAncestorofaBinarySearchTree.cpp
Day-62/TwoSumIVInputisaBST.cpp

Day-62 completed

---

Day-63/BinarySearchTreetoGreaterumTree.cpp
Day-63/ConstructBinarySearchTreefromPreorderTraversal.cpp
Day-63/ValidateBinarySearchTree.cpp

Day-63 completed

---

Day-64/MinimumDeletionstoMakeCharacterFrequenciesUnique.cpp
Day-64/QueueReconstructionbyHeight.cpp

Day-64 completed

---

Day-65/MaximumPointsYouCanObtainfromCards.cpp
Day-65/MinimumMovestoEqualArrayElementsII.cpp

Day-65 completed

---

Day-66/MaximumUnitsonaTruck.cpp
Day-66/NondecreasingArray.cpp

Day-66 completed

---

Day-67/BinaryTreeZigzagLevelOrderTraversal.cpp
Day-67/MaximumAreaofaPieceofCakeAfterHorizontalandVerticalCuts.cpp

Day-67 completed

---

Day-68/LongestConsecutiveSequence.cpp
Day-68/WiggleSubsequence.cpp

Day-68 completed

---

Day-69/MaximumDepthofNaryTree.cpp
Day-69/PaintHouseIII.cpp

Day-69 completed

---

Day-70/FirsMissingPositive.cpp
Day-70/MatchstickstoSquare.cpp

Day-70 completed

---

Day-72/KInversePairsArray.cpp
Day-72/OutofBoundaryPaths.cpp

Day-72 completed

---

Day-73/NumberofMatchingSubsequences.cpp
Day-73/NumberofSubmatricesThatSumtoTarget.cpp

Day-73 completed

---

Day-74/BinaryTreeLevelOrderTraversal.cpp
Day-74/ValidateBinarySearchTree.cpp

Day-74 completed

---

Day-75/ChocolateDistributionProblem.cpp
Day-75/NextPermutation.cpp

Day-75 completed

---

Day-76/BestTimetoBuyandSellStock.cpp
Day-76/KthLargestElementinanArray.cpp

Day-76 completed

---

Day-77/ProductofArrayExceptSelf.cpp
Day-77/ValidAnagram.cpp

Day-77 completed

---

.vscode/settings.json
Day-78/4Sum.cpp
Day-78/FindandReplacePattern.cpp

Day-78 completed

---

Day-79/MergeIntervals.cpp
Day-79/RangeSumQueryMutable.cpp

Day-79 completed

---

Day-80/CountNumberofBadPairs.cpp
Day-80/MyCalendarI.cpp

Day-80 completed

---

Day-81/HouseRobber.cpp
Day-81/SortColors.cpp

Day-81 completed

---

Day-82/3SumClosest.cpp
Day-82/AddOneRowtoTree.cpp
Day-82/MyCalendarIII.cpp
Day-82/PathSum.cpp
Day-82/TimeBasedKeyValueStore.cpp

Day-82 completed

---

Day-83/KClosestPointstoOrigin.cpp
Day-83/KthSmallestPrimeFraction.cpp
Day-83/MaximumAveragePassRatio.cpp
Day-83/MinimumTimetoMakeRopeColorful.cpp
Day-83/NumberofDiceRollsWithTargetSum.cpp
Day-83/ReorganizeString.cpp

Day-83 completed
